[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".env.example"
  SECRETS_SCAN_OMIT_KEYS = "RAZORPAY_KEY_SECRET,RAZORPAY_WEBHOOK_SECRET"

[[plugins]]
  package = "@netlify/plugin-nextjs"